### ISSUE TITLE
Hide "mute" label after username

### ISSUE THREAD

**Issue by bekoeppel** [g3rv4/Refined#11]
Hi! Thanks for the great extension - I mainly use the "Threads on channel by default" feature. But I don't use the muting feature.

I see a "mute" label after every username:
![image](https://user-images.githubusercontent.com/1185824/46156395-b5b26980-c279-11e8-8655-229c85b708e0.png)

It would be great to have a setting to disable showing this.

**Comment by g3rv4** [comment]
oooh, I see... it's def an issue when using the collapsed mode. I'll have a setting for it today ;)

**Comment by g3rv4** [comment]
Done! I've shipped v1.3.6.3 to Chrome and Firefox (Opera takes 2-3 days to update). If you use one of those versions, you should get an update in 30-45 minutes.

Thanks for your feedback!

PS: If you like the extension, I'd love a review on the store if you can spare a couple minutes ;)
