### ISSUE TITLE
In the "New Threads" view, "Also send as direct message" is not ticked

### ISSUE THREAD

**Issue by bekoeppel** [g3rv4/Refined#15]
In the "New Threads" view, "Also send as direct message" is not ticked:

![screencast_loosejaw_2018-10-08_09-59-54](https://user-images.githubusercontent.com/1185824/46597635-4c382380-cae1-11e8-8640-2584d66a4e5e.gif)

**Comment by g3rv4** [comment]
can you check it is ticked? I’ve rewritten all the functionalities as plugins and it may have messed up things.

Make sure you have these two items checked: https://taut.rocks/reply-to-channel and let me know.

Please also include the browser.

Thanks!

**Comment by g3rv4** [comment]
ouch... my bad... I just notice where that is... I'll work on a fix (I changed the way I intercept the checkbox to be more performant, but missed this case).

sorry and thank you!

**Comment by g3rv4** [comment]
thanks for the report! this is fixed on v2.0.2. It's already available on the Chrome store and about to hit Firefox.

Opera... may take a couple days.

**Comment by bekoeppel** [comment]
Tested it, works :+1: thanks!
