### ISSUE TITLE
Firefox extension is not working with version 2.0.3 (October 15th, 2018)

### ISSUE THREAD

**Issue by oscard0m** [g3rv4/Refined#16]
# Description
Firefox Extension is not working with version `2.0.3` (October 15th, 2018).
**Versions tested:**
*Firefox Developer Edition 63.0b14* 
*Firefox 62.0.3 (64-bit)*

**Operating System:**
macOS Sierra Version 10.12.6

# Details
Besides the extension is installed and enabled, the extension is not showing up in the top bar and none of the enabled features of Slack are not working. Seems like it's not taking any action.

**Comment by g3rv4** [comment]
hmm, that's interesting... the only thing that I can think of (since it's working for me on 62.0.3) is that maybe the extension was updated while you were at slack... in that case, you wouldn't see its icon on the address bar (although the injected content should still work).

If you refresh slack, does it fix it?

**Comment by oscard0m** [comment]
I tried the refresh and still not working. I will try to debug later and get more data on it.

**Comment by g3rv4** [comment]
hmmm... that's no fun. Thank you very much for any help debugging it!

if there are issues, it could be on Slack's console or on the background script's console. You need to `about:debugging`, tick "Enable add-on debugging" and then go to the extension and click on "Debug" to see what's going on on the background script.

Thanks again!

**Comment by oscard0m** [comment]
Hi @g3rv4! I don't know why but it's not happening anymore... I'm so sorry I could not provide more info on why was it happening. In any case, we can close the issue I guess.

Thanks for your help and fast answer!

**Comment by g3rv4** [comment]
thanks for writing back! if it happens again, I’d love to see if there are errors in the console ;)
