### ISSUE TITLE
Don't modify text inside code blocks

### ISSUE THREAD

**Issue by gbrayut** [g3rv4/Refined#20]
I'm not on the latest release, but at least on the version I have now it will still convert `[a](b)` text to `<b|a>` inside ` ``` ` style code blocks.

![image](https://user-images.githubusercontent.com/304401/51343677-21e8f100-1a54-11e9-9558-1d3954b7f808.png)

Not a huge deal (code snippets still work) but worth trying to exclude those areas.

**Comment by g3rv4** [comment]
Can you please update to 2.2.3.1 and check if this is correctly fixed?

Thanks!

**Comment by g3rv4** [comment]
@gbrayut I updated Refined and checked the exact content you pasted and this is what I got:

![](https://gmc.uy/notModifyingCode.png)

So I'm closing this one... let me know if you find more weirdness with it.
