### ISSUE TITLE
Send to #channel suddenly stopped working #3

### ISSUE THREAD

**Issue by bekoeppel** [g3rv4/Refined#21]
Since today, my "Send to #channel" doesn't work anymore. The box is just always un-ticked, as if the extension wasn't running.

I have the following setting:
- Threads on channel by default: ON
- Make "send to channel" sticky: ON

![image](https://user-images.githubusercontent.com/1185824/51936951-a3079700-2409-11e9-8f51-994bfd59bede.png)

I don't see any errors in the console log of Slack, or in the background page console log of the plugin.

**Comment by g3rv4** [comment]
I was able to reproduce the issue... working on a fix ;)

**Comment by g3rv4** [comment]
@bekoeppel shipped v2.2.3.2 to Chrome and Firefox (Opera takes ages). Can you please update and let me know if it's fixed?

Thanks!

**Comment by bekoeppel** [comment]
Awesome, thanks for the fast fix! Works again :-)

**Comment by bekoeppel** [comment]
Hi @g3rv4. I just noticed that it doesn't fully work. The checkbox for "Also send to #channel" is now ticked automatically, but then when sending the message, it is _not_ sent to the channel. If I untick the checkbox, and tick it again (by clicking on it), then it works.

**Comment by g3rv4** [comment]
ugh, our good friends at Slack changing things again... checking it out

**Comment by g3rv4** [comment]
@bekoeppel alright... I fixed it on commit a465f7a using [this ugly hack](https://github.com/facebook/react/issues/11488#issuecomment-347775628).

I'm very tempted to kill those 2 features. The main reason to do it is...  I don't use them anymore since I added the ability to [broadcast all the messages](https://refined.chat/broadcast-thread).

I'm working on improving it a little bit. How sad (on a scale of 1-10) would you be if I did indeed kill those features?

Please update to v2.2.3.3 and let me know if it's working for you now.

**Comment by bekoeppel** [comment]
@g3rv4 great, thanks! I tried v2.2.3.3, and it works again. 

> I'm working on improving it a little bit. How sad (on a scale of 1-10) would you be if I did indeed kill those features?

My sadness would be ∞. Thats the only feature I use from your extension at the moment, and it perfectly solves my need of always having "Respond to #channel" turned on. 

The broadcast feature and keeping multiple channels open in multiple tabs wouldn't really work for me. I am in about 100 channels or so, and very often use the Ctrl-K shortcut to open the "Jump to" window to go to another channel quickly. So I would need 100 tabs, and couldn't use Ctrl-K anymore, because I would have to check another tab instead.

**Comment by g3rv4** [comment]
alright, infinite level of sadness is definitely too much.

They’re staying :) thanks for verifying the fix!

**Comment by g3rv4** [comment]
@bekoeppel would you mind [checking visible threads](https://refined.chat/visible-threads)? it's the same feature but improved greatly (now you don't need to keep different channels open in different tabs, stuff works exactly as I would expect it to).
