### ISSUE TITLE
Safari extension?

### ISSUE THREAD

**Issue by evandrix** [g3rv4/Refined#22]
# Thanks for reporting a bug!

Each feature in the extension is a plugin. It would be super helpful if you investigated
which plugin is causing the bug.

How can you do so? disable a feature and check if the bug still persists. If it does, disable
another one and check if the bug persists.

Once you disable a feature and the bug disappears, that's the feature with the bug!

### System configuration
**Browser (include version)**:

**Operating System (include version)**:

**Comment by g3rv4** [comment]
hi there!

Safari’s extension model is totally different from Chrome / Firefox... and as I don’t use it, I don’t have lots of incentives to work on it.

Thanks for the suggestion though! and if you want to steal ideas and write your own extension, by all means go ahead! and let me know if I can help.
