### ISSUE TITLE
Visible threads loosing indicative arrow and behavior

### ISSUE THREAD

**Issue by juanrodriguezcen** [g3rv4/Refined#23]
### Involved feature
Visible threads

### Steps to reproduce
The arrow that shows that a message is a reply, as well as the highlighting behavior, are lost when browsing: Channel > All Threads > Channel. The replies still show up in the Channel, however you can't discriminated from initial messages. 

However, if I move between channels, this is not a problem.

### Expected behavior
The arrow and highlighting behavior should keep working with browsing Channel > All Threads > Channel

### System configuration
**Browser (include version)**: Chrome 71.0.3578.98

**Operating System (include version)**: Windows

**Comment by g3rv4** [comment]
please upgrade to 2.2.5.5 and let me know if it's fixed :)

**Comment by juanrodriguezcen** [comment]
Works great now 👍

Thanks!
