### ISSUE TITLE
Visible threads - Reply disappears after editing it

### ISSUE THREAD

**Issue by juanrodriguezcen** [g3rv4/Refined#24]
### Involved feature
Visible threads

### Steps to reproduce
Edit a reply from a thread

### Expected behavior
The edited reply will still show up

### Actual behavior
The edited reply disappears but if you open the thread the reply is in there, it is just removed from the channel view

### System configuration
**Browser (include version)**: Chrome 71.0.3578.98

**Operating System (include version)**: Windows

**Comment by g3rv4** [comment]
please upgrade to 2.2.5.5 and let me know if it's fixed :)

**Comment by juanrodriguezcen** [comment]
The edited reply still shows up, but the "arrow" disappears, however the thead highlight while hovering works.

**Comment by g3rv4** [comment]
Repro here:

![](https://gervas.io/repro.gif)

**Comment by g3rv4** [comment]
@juanrodriguezcen can you check if this is fixed on 2.2.5.9? thanks!
