### ISSUE TITLE
Request : easy post reaction "à la" Mattermost

### ISSUE THREAD

**Issue by glc-mvion** [g3rv4/Refined#26]
In Mattermost you can react to last posted message by sending a `+` symbol followed by the emoji name, by example, to react with joy you send `+:joy:` and it automatically set the reaction to the last message.

I think it could be a nice feature to have and your extension could be a nice place to put it (:

Also I would like to contribute myself to the implementation of the feature so if you could indicate me where I should start it would be perfect !

(also thank you for having developed this extension !)

**Comment by g3rv4** [comment]
hi Matt!

Thanks for the idea :) doesn’t it work like that in Slack as well? I’m pretty sure I’ve used it.

Right now, I wouldn’t know how to identify the “last message” (also, it’s a different one if the side panel is open and the user is typing there)... but that only means implementing it would be fun!

Check out if the feature doesn’t work like that in Slack, and if it doesn’t let’s discuss a bit how you could intercept that.

**Comment by glc-mvion** [comment]
My bad, I should have checked before, it seems to work like I described it !

Sorry for the time wasted ! :bowing_man:

**Comment by g3rv4** [comment]
no worries, I’m happy to see you like the extension enough to consider contributing to it <3
