### ISSUE TITLE
Problems with Visible Thread reply indicators

### ISSUE THREAD

**Issue by abliss** [g3rv4/Refined#34]
Thanks for making this awesome extension! I have two small bugs to report:

### Involved feature
Visible Threads
### Steps to reproduce
turn on Visible Threads.

1. have somebody else post a reply comment which contains only an image. It does not get a "this is a reply" arrow when it shows up in the main chat.
2. have somebody else post a regular reply comment with text. It gets the "this is a reply" arrow icon.
3. press ctrl-F6 to switch focus to the messages pane, and use the up-arrow to scroll up to focus the reply. Then keep going up, and come back down to focus the reply. Each time the item gets focused, it gains an extra reply arrow icon.

### Expected behavior
Replies which are only images should still get the icon, just like text replies.
Text replies should get just one icon, and the icon shouldn't be duplicated each time the message is focused.

### Actual behavior
Replies which are only images don't get the icon.
Text replies get a new icon each time the message is focused.

### System configuration
** Browser version** :Google Chrome	73.0.3683.103 (Official Build) (64-bit)
**Extension version**: 2.2.6

**Comment by g3rv4** [comment]
Thanks! nice catch :) I will look into it whenever I have some time (I have a 3-months-old at home, so time is hard to come by).

If you want to take a stab at it, I can offer ideas.

**Comment by g3rv4** [comment]
Done! fixed in 2.2.9. That version is available on Chrome now (and it will be on Firefox as soon as they fix [their certificate shenanigans](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047)).

If you enjoy the extension, a review on the store would be highly appreciated :)
