### ISSUE TITLE
Feature Request : Reaction avatars (like RefinedGithub)

### ISSUE THREAD

**Issue by dorian-marchal** [g3rv4/Refined#37]
This would be a nice feature. :slightly_smiling_face: 

![Screenshot from 2019-05-22 15-18-53](https://user-images.githubusercontent.com/6225979/58177597-f5b0db80-7ca4-11e9-8da6-4a9de3c49148.png)

**Comment by g3rv4** [comment]
heh, I have all what's needed to make this happen... except for designing skills. If you could provide HTML for it (and indications of where to put it in the DOM) I could _some day_ work on it :)

Also: this is something I'd gladly merge a PR for (it should be its own plugin)

**Comment by g3rv4** [comment]
I'm continuing the development of the extension in private :( read more about it [on my blogpost](https://g3rv4.com/2019/07/bye-bye-refined)
