### ISSUE TITLE
Markdown Links no longer working

### ISSUE THREAD

**Issue by HeyBillFinn** [g3rv4/Refined#39]
### Involved feature

Markdown Links

### Steps to reproduce

Send a message with [test markdown links](https://refined.chat/markdown-links).

### Expected behavior

[test markdown links](https://refined.chat/markdown-links) is rendered.

### Actual behavior

`[test markdown links](https://refined.chat/markdown-links)` is rendered

### System configuration

**Browser (include version)**: Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)
**Extension version**: Refined v2.2.18

**Comment by g3rv4** [comment]
I'm unable to repro... which is not a bad thing, it means they kept the API there and we should be able to fix it.

Unfortunately, without a repro I can't work on a fix. Have you tried refreshing slack?

**Comment by HeyBillFinn** [comment]
> Unfortunately, without a repro I can't work on a fix. Have you tried refreshing slack?

Yes, I tried refreshing Slack, and the issue remains. Coincidentally, a colleague of mine reported the same problem yesterday, and I was unable to reproduce.

I wonder if Slack is slowly rolling out changes to its users. Is there anything helpful I can capture from the javascript console or javascript source?

**Comment by g3rv4** [comment]
welp, I should get it soon enough :) I also heard colleagues talk about Slack doing architecture modifications to their web app.

If you have errors there, yeah... but I'm going to guess that there are none (and that they replaced the function I'm monkey patching).

**Comment by HeyBillFinn** [comment]
Ok, sounds good -- fwiw, you're correct that there are no javascript errors.

**Comment by g3rv4** [comment]
I was able to reproduce the issue... I'm ashamed to admit that even if you clearly stated you were using Chrome, I tried to get a repro on Firefox 🤦‍♂ 

It works on Firefox, it's broken on Chrome. I'll work on fixing it this weekend.

**Comment by g3rv4** [comment]
it doesn’t look amazing :( https://twitter.com/g3rv4/status/1152629175108460545

it certainly seems like they are actively making it really hard for extensions to mess with their site

**Comment by g3rv4** [comment]
I'm continuing the development of the extension in private :( read more about it [on my blogpost](https://g3rv4.com/2019/07/bye-bye-refined)
