### ISSUE TITLE
Unable to Mute a User.

### ISSUE THREAD

**Issue by tomas-samot** [g3rv4/Refined#40]
### Involved feature
Unable to mute a user.

### Steps to reproduce
Follow the steps here and the mute button is not shown.
https://refined.chat/mute-users#muting

### Expected behavior
Mute button should show.

### Actual behavior
Mute button is not shown.

### System configuration
**Browser (include version)**: Chrome 75.0.3770.142
**Extension version**: 2.2.18

**Comment by g3rv4** [comment]
Hi Tomas,

This is a known issue... most of the features are broken if you land on the new slack version (that is, if you’re redirected to app.slack.com)

I’m not sure which features I’ll be able to bring back to life, I’m also not sure when that would happen (I’d love to say next Monday, but I spent some time this weekend with little to show for it).

Long story short: Slack rewrote their web app exposing as little of it as possible for extensions to mess with it.

**Comment by tomas-samot** [comment]
My condolences. Your extension makes using Slack bearable. It will be disappointing if Slack start actively trying to stop extensions from modifying the experience.

**Comment by g3rv4** [comment]
I'm continuing the development of the extension in private :( read more about it [on my blogpost](https://g3rv4.com/2019/07/bye-bye-refined)
