### ISSUE TITLE
Make BetterSlack work with Mattermost

### ISSUE THREAD

**Issue by straff2002** [g3rv4/Refined#7]
We've started using [Mattermost](https://mattermost.com/) due to its Slack features with the ability to self-determine what will work with it. I'm wondering if there's the capability to make it work with mattermost as it will use Slack add-ons that have been tweaked?

**Comment by g3rv4** [comment]
BetterSlack is extremely reliant on the way Slack is implemented... so no, it can't easily be ported.

However, I'm sure you can take ideas about how to inspect and modify ajax requests and websockets... after all, that's how all they play their tricks.

As I'm not a Mattermost user, it's not something I'd be interested in contributing to.
